name: Trigger auto deployment for drupal-10-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/drupal-10-aca-AutoDeployTrigger-87a9b313-20b6-4982-a6bc-26c4876a08be.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DRUPAL10ACA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DRUPAL10ACA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DRUPAL10ACA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: drupalacr.azurecr.io
          registryUsername: ${{ secrets.DRUPAL10ACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DRUPAL10ACA_REGISTRY_PASSWORD }}
          containerAppName: drupal-10-aca
          resourceGroup: CMS_Drupal
          imageToBuild: drupalacr.azurecr.io/drupal-10-aca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


